### ISSUE TITLE
Rare formulering bij vraag 4

### ISSUE THREAD

**Issue by RobinHaveneers** [Jense5/a-b#1]
Onder de figuur bij vraag 4 (pagina 9) staat in puntje 1 van de opsomming "Indien E nu \<M,s\> accepteert." Dit is een rare formulering aangezien er met "indien" meestal een gevolg komt zoals "indien (...) dan". De zin lijkt onvolledig. Revisie is nodig.

**Comment by Jense5** [comment]
Zie ik nergens staan, looks like solved to me.
